//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
// Developed jointly by NASA/GSFC and Thinking Systems, Inc. under contract
// number S-67573-G
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONFIGMANAGEREXCEPTION_HPP
#define CONFIGMANAGEREXCEPTION_HPP

#include "BaseException.hpp" // inheriting class's header file

/**
 * Exceptions thrown by the Configuration Manager
 */
class ConfigManagerException : public BaseException
{
	public:
		// class constructor
		ConfigManagerException(std::string details);
		// class destructor
		~ConfigManagerException();
};

#endif // CONFIGMANAGEREXCEPTION_HPP

