//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
// Developed jointly by NASA/GSFC and Thinking Systems, Inc. under contract
// number S-67573-G
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------

// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONFIGMANAGER_HPP
#define CONFIGMANAGER_HPP

#include <vector>
#include <map>

#include "ForceModel.hpp"
#include "Subscriber.hpp"
#include "SolarSystem.hpp"
#include "CelestialBody.hpp"
#include "PropSetup.hpp"
#include "Spacecraft.hpp"
#include "StopCondition.hpp"
#include "PhysicalModel.hpp"
#include "Propagator.hpp"
#include "Parameter.hpp"
#include "Command.hpp"
#include "Burn.hpp"
#include "Solver.hpp"
#include "AtmosphereModel.hpp"
#include "Function.hpp"
#include "Hardware.hpp"
#include "CoordinateSystem.hpp"

//djc: 11/10/04 - added Hardware
//loj: 01/18/05 - added CoordinateSystem

/**
 * Configuration Manager Stub -- a hack until the real code is ready
 */
class ConfigManager
{
public:
   static ConfigManager*   Instance(void);
   
   void                AddPhysicalModel(PhysicalModel *pm);
   void                AddPropagator(Propagator *prop);
   void                AddForceModel(ForceModel *fm);
   void                AddSubscriber(Subscriber *subs);
   void                AddSolarSystem(SolarSystem *solarSys);
   void                AddPropSetup(PropSetup *propSetup);
   void                AddSpacecraft(SpaceObject *sc);
   void                AddHardware(Hardware *hw);
   void                AddStopCondition(StopCondition* stopCond);
   void                AddParameter(Parameter* parameter);
   void                AddBurn(Burn* burn);
   void                AddSolver(Solver *solver);
   void                AddAtmosphereModel(AtmosphereModel *atmosModel);
   void                AddFunction(Function *function);
   void                AddCoordinateSystem(CoordinateSystem *cs);
   
   bool                SetSolarSystemInUse(const std::string &name);
   
   StringArray&        GetListOfAllItems();
   StringArray&        GetListOfItems(Gmat::ObjectType itemType);// const;
   GmatBase*           GetItem(const std::string &name);
    
   bool                RenameItem(Gmat::ObjectType itemType,
                                  const std::string &oldName,
                                  const std::string &newName);
   
   bool                RemoveAllItems();
   bool                RemoveItem(Gmat::ObjectType type, const std::string &name);
   
   PhysicalModel*      GetPhysicalModel(const std::string &name);
   Propagator*         GetPropagator(const std::string &name);
   ForceModel*         GetForceModel(const std::string &name);
   SpaceObject*        GetSpacecraft(const std::string &name);
   Hardware*           GetHardware(const std::string &name);
   PropSetup*          GetPropSetup(const std::string &name);
   Subscriber*         GetSubscriber(const std::string &name);
   SolarSystem*        GetDefaultSolarSystem();
   SolarSystem*        GetSolarSystemInUse();
   StopCondition*      GetStopCondition(const std::string &name);
   Parameter*          GetParameter(const std::string &name);
   Burn*               GetBurn(const std::string &name);
   Solver*             GetSolver(const std::string &name);
   AtmosphereModel*    GetAtmosphereModel(const std::string &name);
   Function*           GetFunction(const std::string &name);
   CoordinateSystem*   GetCoordinateSystem(const std::string &name);
   
   // Methods I'm not sure we need
   void                AddCelestialBody(CelestialBody* body);
   void                AddCommand(GmatCommand *cmd);
   CelestialBody*      GetCelestialBody(const std::string &name);
   GmatCommand*        GetCommand(const std::string name);
   
private:
   
   /// The singleton instance
   static ConfigManager*   theConfigManager;
   ConfigManager();
   ~ConfigManager();
   
   std::vector<GmatBase*>  objects;
   StringArray  listOfItems;
   std::map<std::string, GmatBase *>  mapping;
};


#endif // CONFIGMANAGER_HPP

