# Project:    GMAT
# Module:     Makefile.mac for solver directory 
# Created:    Joey Gurgnaus 
# Date:       2003/11/13
# Modified:   2003/01/16 - Added new cpp files


# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC = DifferentialCorrector.cpp Solver.cpp SolverException.cpp
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/base/inc.mac
include ${INCMK}
#
