
Create GmatFunction cross;

Create Array crossProd[3,1] vec1[3,1] vec2[3,1]

Create ReportFile rf

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;

vec1(1,1) = 0.5;
vec1(2,1) = -0.5;
vec1(3,1) = 0.75;

vec2(1,1) = 1.5;
vec2(2,1) = -5.5;
vec2(3,1) = 7.75;

[crossProd] = cross(vec1,vec2)

Report rf crossProd