# Tools
fop = ./contrib/fop/fop
rm = rm -f

# Build Xalan classpath
xalancp = "contrib/xalan-j/xalan.jar:contrib/xalan-j/serializer.jar:\
	contrib/xalan-j/xml-apis.jar:contrib/xalan-j/xercesImpl.jar:\
	contrib/docbook-xsl-ns/extensions/xalan27.jar"

include Common.mk