#!/bin/sh

# build Xalan classpath
xalancp='contrib/xalan-j/xalan.jar:contrib/xalan-j/serializer.jar'
xalancp=${xalancp}':contrib/xalan-j/xml-apis.jar:contrib/xalan-j/xercesImpl.jar'
xalancp=${xalancp}':contrib/docbook-xsl-ns/extensions/xalan27.jar'

# set Java options
xmlparser='org.apache.xerces.parsers.XIncludeParserConfiguration'

# validate the XML
echo 'Validating document...'
java \
    -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=${xmlparser} \
    -jar contrib/jing/bin/jing.jar \
	'http://www.docbook.org/xml/5.0/rng/docbookxi.rng' \
	src/help.xml
echo '--------------------'
echo

# DocBook -> XSL-FO -> PDF (letter)
echo 'PDF (letter)'
java -cp ${xalancp}	\
	-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=${xmlparser} \
	org.apache.xalan.xslt.Process \
	-IN src/help.xml \
	-XSL contrib/docbook-xsl-ns/fo/docbook.xsl \
	-OUT build/help-letter.fo
sh contrib/fop/fop build/help-letter.fo build/help-letter-fo.pdf
echo '--------------------'
echo

# DocBook -> XSL-FO -> PDF (A4)
echo 'PDF (A4)'
java -cp ${xalancp}	\
	-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=${xmlparser} \
	org.apache.xalan.xslt.Process \
	-IN src/help.xml \
	-XSL contrib/docbook-xsl-ns/fo/docbook.xsl \
	-OUT build/help-a4.fo
sh contrib/fop/fop build/help-a4.fo build/help-a4-fo.pdf
echo '--------------------'
echo

# DocBook -> LaTeX -> PDF (letter)
echo 'LaTeX PDF (letter)'
dblatex -o build/help-letter-latex.pdf \
	-P latex.class.options=letterpaper \
	src/help.xml
echo '--------------------'
echo

# DocBook -> LaTeX -> PDF (A4)
echo 'LaTeX PDF (A4)'
dblatex -o build/help-a4-latex.pdf \
	-P latex.class.options=a4paper \
	src/help.xml
echo '--------------------'
echo

# DocBook -> HTML (single page)
echo 'HTML (single page)'
java -cp ${xalancp}	\
	-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=${xmlparser} \
	org.apache.xalan.xslt.Process \
	-IN src/help.xml \
	-XSL contrib/docbook-xsl-ns/xhtml-1_1/docbook.xsl \
	-OUT build/help.html
echo '--------------------'
echo

# DocBook -> HTML (multiple pages)
echo 'HTML (multiple pages)'
java -cp ${xalancp}	\
	-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=${xmlparser} \
	org.apache.xalan.xslt.Process \
	-PARAM base.dir ../build/html/ \
	-IN src/help.xml \
	-XSL contrib/docbook-xsl-ns/xhtml-1_1/chunk.xsl
echo '--------------------'
echo