# Tools
fop = sh ../build/contrib/fop/fop
rm = rm -rf

# Build Xalan classpath
xalancp = "../build/contrib/xalan-j/xalan.jar:\
	../build/contrib/xalan-j/serializer.jar:\
	../build/contrib/xalan-j/xml-apis.jar:\
	../build/contrib/xalan-j/xercesImpl.jar:\
	../build/contrib/docbook-xsl-ns/extensions/xalan27.jar"

include Common.mk

# Custom rules
clean :
	$(rm) *.fo *.pdf files
