# $Id: Makefile 9461 2012-08-17 16:57:15Z tuannguyen $
# GMAT: General Mission Analysis Tool.
# 
#  Copyright (c) 2002-2014 United States Government as represented by the
#  Administrator of The National Aeronautics and Space Administration.
#  All Other Rights Reserved.
#
# src level makefile 
#
# This file calls make on the src subfolders.

all: 
	cd base; make all

clean:
	cd base; make clean
