addpath('./measurements/tdrss','./measurements/tdrss/sample_data/',...
    './Truth/TDRSS','./constants','./dynamics','./math','./time','./utilities',...
    './utilities/mercator','./utilities/Vallado');
run_tdrss_doppler;
rmpath('./measurements/tdrss','./measurements/tdrss/sample_data/',...
    './Truth/TDRSS','./constants','./dynamics','./math','./time','./utilities',...
    './utilities/mercator','./utilities/Vallado');
