# $Id: Makefile 126 2010-03-25 22:06:28Z djconway@NDC $
# Root level makefile 
#
# This file calls make on the src folder.

all: 
	cd src; make all

rebuild: 
	cd src; make clean; make all

clean:
	cd src; make clean
