# Project:    GMAT
# Module:     Makefile.mac for burn directory 
# Created:    Joey Gurgnaus 
# Date:       2004/02/18
# Modified:   2004/05/10 - Changed to using wildcard *.cpp
#
#
# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC := $(wildcard *.cpp)
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/gui/inc.mac
include ${INCMK}
#
