
// GmatUtil

#include "utildefs.hpp"
#include "BaseException.hpp"

#include "Date.hpp"
//#include "DateUtil.hpp"
#include "A1Date.hpp"
#include "A1Mjd.hpp"
#include "AngleUtil.hpp"
#include "ArrayTemplate.hpp"
#include "AttitudeConversionUtility.hpp"
#include "BodyFixedStateConverter.hpp"
#include "CalculationUtilities.hpp"
#include "CCSDSEMReader.hpp"
#include "CCSDSEMSegment.hpp"
#include "CCSDSAEMReader.hpp"
#include "CCSDSAEMSegment.hpp"
#include "CCSDSAEMEulerAngleSegment.hpp"
#include "CCSDSAEMQuaternionSegment.hpp"
#include "Code500EphemerisFile.hpp"
#include "ColorDatabase.hpp"
#include "ElapsedTime.hpp"
#include "EopFile.hpp"
#include "FileManager.hpp"
#include "Frozen.hpp"
#include "GmatDefaults.hpp"
#include "GmatGlobal.hpp"
#include "GmatTime.hpp"
#include "GravityFileUtil.hpp"
#include "GregorianDate.hpp"
//#include "Linear.hpp"
#include "MemoryTracker.hpp"
#include "OrbitDesignerTime.hpp"
#include "RealUtilities.hpp"
#include "RepeatGroundTrack.hpp"
#include "RepeatSunSync.hpp"
#include "RgbColor.hpp"
#include "TableTemplate.hpp"
#include "Rmatrix.hpp"
#include "Rmatrix33.hpp"
#include "Rmatrix66.hpp"
#include "Rvector.hpp"
#include "Rvector3.hpp"
#include "Rvector6.hpp"

// Declare friend functions
GMATUTIL_API Rmatrix  SkewSymmetric4by4(const Rvector3& v);
GMATUTIL_API Rmatrix33  SkewSymmetric(const Rvector3& v);
GMATUTIL_API Rmatrix66  SkewSymmetric(const Rvector6& v);

#include "StateConversionUtil.hpp"
#include "StringTokenizer.hpp"
#include "SunSync.hpp"
#include "TextParser.hpp"
#include "TimeSystemConverter.hpp"
#include "TimeTypes.hpp"
#include "UtcDate.hpp"

#include "Interpolator.hpp"
#include "BrentDekkerZero.hpp"
#include "CubicSplineInterpolator.hpp"
#include "HermiteInterpolator.hpp"
#include "LagrangeInterpolator.hpp"
#include "LinearInterpolator.hpp"
#include "NotAKnotInterpolator.hpp"

// GmatBase

#include "gmatdefs.hpp"

#include "GmatBase.hpp"
#include "GmatState.hpp"
#include "Covariance.hpp"
#include "StateManager.hpp"
#include "SpacePoint.hpp"

#include "Attitude.hpp"
#include "Kinematic.hpp"
#include "CSFixed.hpp"
#include "CCSDSAttitude.hpp"
#include "NadirPointing.hpp"
#include "PrecessingSpinner.hpp"
#include "SpiceAttitude.hpp"
#include "Spinner.hpp"

#include "Burn.hpp"
#include "ManeuverFrame.hpp"
#include "FiniteBurn.hpp"
#include "ImpulsiveBurn.hpp"
#include "InertialManeuverFrame.hpp"
#include "ManeuverFrameManager.hpp"
#include "VnbManeuverFrame.hpp"

#include "PhysicalModel.hpp"
#include "DragForce.hpp"
//#include "EventModel.hpp"
#include "FiniteThrust.hpp"
#include "GravityBase.hpp"
#include "HarmonicField.hpp"
#include "GravityField.hpp"
#include "ODEModel.hpp"
#include "PointMassForce.hpp"
#include "RelativisticCorrection.hpp"
#include "SolarRadiationPressure.hpp"

#include "MathNode.hpp"
#include "MathFunction.hpp"
#include "Abs.hpp"
#include "Acos.hpp"
#include "Acosh.hpp"
#include "Add.hpp"
#include "Asin.hpp"
#include "Asinh.hpp"
#include "Atan.hpp"
#include "Atan2.hpp"
#include "Cos.hpp"
#include "Cosh.hpp"
#include "DegToRad.hpp"
#include "Determinant.hpp"
#include "Divide.hpp"
#include "Exp.hpp"
#include "FunctionRunner.hpp"
#include "Inverse.hpp"
#include "Log.hpp"
#include "Log10.hpp"
#include "MathElement.hpp"
#include "Multiply.hpp"
#include "Negate.hpp"
#include "Norm.hpp"
#include "Power.hpp"
#include "RadToDeg.hpp"
#include "Sin.hpp"
#include "Sinh.hpp"
#include "Sqrt.hpp"
#include "Subtract.hpp"
#include "Tan.hpp"
#include "Tanh.hpp"
#include "Transpose.hpp"

#include "BodyFixedPoint.hpp"
#include "GroundstationInterface.hpp"

#include "CoordinateBase.hpp"
#include "CoordinateSystem.hpp"
#include "AxisSystem.hpp"
   
#include "DynamicAxes.hpp"
   
#include "BodyFixedAxes.hpp"
#include "EquatorAxes.hpp"
#include "ITRFAxes.hpp"
#include "LocalAlignedConstrainedAxes.hpp"
   
#include "MeanOfDateAxes.hpp"
#include "MODEcAxes.hpp"
#include "MODEqAxes.hpp"
   
#include "TrueOfDateAxes.hpp"
#include "TODEcAxes.hpp"
#include "TODEqAxes.hpp"

#include "TopocentricAxes.hpp"

#include "ObjectReferencedAxes.hpp"
#include "BodySpinSunAxes.hpp"
#include "GeocentricSolarEclipticAxes.hpp"

#include "InertialAxes.hpp"
#include "BodyInertialAxes.hpp"
#include "ICRFAxes.hpp"
#include "MJ2000EcAxes.hpp"
#include "MJ2000EqAxes.hpp"
#include "TOEEcAxes.hpp"
#include "TOEEqAxes.hpp"

#include "IAUFile.hpp"
#include "ICRFFile.hpp"
#include "ItrfCoefficientsFile.hpp"
   
#include "CoordinateConverter.hpp"
   
#include "CelestialBody.hpp"
#include "Asteroid.hpp"
#include "Comet.hpp"
#include "Moon.hpp"
#include "Planet.hpp"
#include "SpecialCelestialPoint.hpp"
#include "Star.hpp"
   
#include "CalculatedPoint.hpp"
#include "Barycenter.hpp"
#include "LibrationPoint.hpp"
   
#include "AtmosphereModel.hpp"
#include "ExponentialAtmosphere.hpp"
#include "JacchiaRobertsAtmosphere.hpp"
#include "Msise90Atmosphere.hpp"
#include "SimpleExponentialAtmosphere.hpp"

#include "PlanetaryEphem.hpp"
#include "DeFile.hpp"

#include "ShadowState.hpp"
#include "SolarFluxReader.hpp"
   
#include "SolarSystem.hpp"
   
#include "GmatCommand.hpp"
#include "BranchCommand.hpp"
#include "ConditionalBranch.hpp"
#include "SolverBranchCommand.hpp"
#include "ManageObject.hpp"
#include "PropagationEnabledCommand.hpp"
#include "SolverSequenceCommand.hpp"
#include "Achieve.hpp"
#include "Assignment.hpp"
#include "BeginFiniteBurn.hpp"
#include "BeginFunction.hpp"
#include "BeginMissionSequence.hpp"
#include "BeginScript.hpp"
#include "CallFunction.hpp"
#include "CallBuiltinGmatFunction.hpp"
#include "FindEvents.hpp"
#include "CommandUtil.hpp"
#include "ClearPlot.hpp"
#include "Create.hpp"
#include "Else.hpp"
#include "EndFiniteBurn.hpp"
#include "EndFor.hpp"
#include "EndFunction.hpp"
#include "EndIf.hpp"
#include "EndOptimize.hpp"
#include "EndScript.hpp"
#include "EndTarget.hpp"
#include "EndWhile.hpp"
#include "For.hpp"
#include "If.hpp"
#include "Maneuver.hpp"
#include "MarkPoint.hpp"
#include "Minimize.hpp"
#include "NonlinearConstraint.hpp"
#include "NoOp.hpp"
#include "Optimize.hpp"
#include "PenDown.hpp"
#include "PenUp.hpp"
#include "Propagate.hpp"
#include "PlotCommand.hpp"
#include "RHSEquation.hpp"
#include "Report.hpp"
#include "RunSolver.hpp"
#include "SaveMission.hpp"
#include "Stop.hpp"
#include "Target.hpp"
#include "Toggle.hpp"
#include "UpdateDynamicData.hpp"
#include "Vary.hpp"
#include "While.hpp"
#include "Write.hpp"

#include "SpaceObject.hpp"
#include "Spacecraft.hpp"
   
#include "Solver.hpp"
#include "Optimizer.hpp"
#include "DerivativeModel.hpp"
#include "DifferentialCorrector.hpp"
#include "ExternalOptimizer.hpp"
#include "Gradient.hpp"
#include "InternalOptimizer.hpp"
// #include "ISolverListener.hpp"
#include "Jacobian.hpp"
#include "LineSearch.hpp"

#include "PropSetup.hpp"
#include "Propagator.hpp"
#include "Integrator.hpp"
#include "PredictorCorrector.hpp"
#include "RungeKutta.hpp"
#include "RungeKuttaNystrom.hpp"
#include "AdamsBashforthMoulton.hpp"
// Non-creatable #include "Cowell.hpp"
#include "DormandElMikkawyPrince68.hpp"
#include "PrinceDormand45.hpp"
#include "PrinceDormand78.hpp"
#include "PropagationStateManager.hpp"
#include "RungeKutta89.hpp"
#include "RungeKuttaFehlberg56.hpp"

/*
#include "Parameter.hpp"
#include "AlternateEquinoctialParameters.hpp"   
#include "AngularParameters.hpp"   
#include "Array.hpp"
#include "ArrayElementWrapper.hpp"
#include "ArrayWrapper.hpp"
//Non-creatable #include "AttitudeData.hpp"
#include "AttitudeParameters.hpp"   
//Non-creatable #include "AttitudeReal.hpp"
//Non-creatable #include "AttitudeRvector.hpp"
//Non-creatable #include "AttitudeString.hpp"
#include "BallisticMassParameters.hpp"
//Non-creatable #include "BallisticMassReal.hpp"
#include "BooleanWrapper.hpp"
//Non-creatable #include "BplaneData.hpp"   
#include "BplaneParameters.hpp"   
//Non-creatable #include "BplaneReal.hpp"   
#include "BrouwerMeanLongParameters.hpp"   
#include "BrouwerMeanShortParameters.hpp"   
//Non-creatable #include "BurnData.hpp"   
#include "BurnParameters.hpp"   
#include "CartesianParameters.hpp"   
#include "DelaunayParameters.hpp"   
//Non-creatable #include "EnvData.hpp"   
//Non-creatable #include "EnvReal.hpp"   
#include "EquinoctialParameters.hpp"   
#include "ExpressionParser.hpp"   
//Non-creatable #include "HardwareReal.hpp"   
#include "HardwareParameters.hpp"   
#include "IncomingAsymptoteParameters.hpp"   
#include "KeplerianParameters.hpp"   
#include "ModEquinoctialParameters.hpp"   
#include "NumberWrapper.hpp"   
#include "ObjectWrapper.hpp"   
#include "ObjectPropertyWrapper.hpp"   
#include "OnOffWrapper.hpp"   
//Non-creatable #include "OrbitData.hpp"   
//Non-creatable #include "OrbitReal.hpp"   
#include "OrbitRmat33.hpp"   
//Non-creatable #include "OrbitRmat66.hpp"   
//Non-creatable #include "OrbitRvec6.hpp"   
#include "OrbitStmParameters.hpp"   
#include "OrbitalParameters.hpp"   
#include "OutgoingAsymptoteParameters.hpp"   
#include "ParameterDatabase.hpp"   
#include "ParameterInfo.hpp"   
#include "ParameterWrapper.hpp"   
//Non-creatable #include "PlanetData.hpp"   
#include "PlanetParameters.hpp"   
//Non-creatable #include "PlanetReal.hpp"   
#include "PlanetodeticParameters.hpp"   
//Non-creatable #include "RealVar.hpp"   
//Non-creatable #include "RefData.hpp"   
//Non-creatable #include "Rmat33Var.hpp"   
//Non-creatable #include "Rmat66Var.hpp"   
//Non-creatable #include "Rvec6Var.hpp"   
//Non-creatable #include "RvectorVar.hpp"   
//Non-creatable #include "SpacecraftData.hpp"   
#include "SphericalParameters.hpp"   
#include "StringObjectWrapper.hpp"   
//Non-creatable #include "TimeData.hpp"
#include "TimeParameters.hpp"
//Non-creatable #include "TimeReal.hpp"
//Non-creatable #include "TimeString.hpp"
#include "Variable.hpp"
#include "VariableWrapper.hpp"
*/

#include "Hardware.hpp"
#include "FuelTank.hpp"
#include "PowerSystem.hpp"
#include "Thruster.hpp"
#include "ChemicalTank.hpp"
#include "ChemicalThruster.hpp"
#include "ElectricTank.hpp"
#include "ElectricThruster.hpp"
#include "NuclearPowerSystem.hpp"
#include "SolarPowerSystem.hpp"

// SPICE accessors
#include "SpiceInterface.hpp"
#include "SpiceKernelReader.hpp"
#include "SpiceOrbitKernelReader.hpp"

#include "EventLocator.hpp"
#include "LocatedEvent.hpp"

#include "StopCondition.hpp"

#include "Subscriber.hpp"
#include "EphemManager.hpp"
#include "EphemerisFile.hpp"
#include "ReportFile.hpp"

   
#include "Interpreter.hpp"
#include "ScriptInterpreter.hpp"
   
#include "DynamicLibrary.hpp"

#include "ConfigManager.hpp"
   
#include "Publisher.hpp"
#include "Sandbox.hpp"
#include "Moderator.hpp"

#include "APIFunctions.hpp"
#include "APIException.hpp"
#include "HelpSystem.hpp"
