# Project:    GMAT
# Module:     Makefile.mac for mission directory 
# Created:    Joey Gurgnaus 
# Date:       2004/02/18
#
#
# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC = DecoratedTree.cpp MissionTree.cpp
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/gui/inc.mac
include ${INCMK}
#
