# $Id$
# 
# GMAT: General Mission Analysis Tool.
# 
#  Copyright (c) 2002-2014 United States Government as represented by the
#  Administrator of The National Aeronautics and Space Administration.
#  All Other Rights Reserved.
#
# GmatFunction makefile 
#
# This file calls make on the base folder.

all: 
	cd base; make all

rebuild: 
	cd base; make clean; make all

clean:
	cd base; make clean
