# $Id: Makefile 7883 2010-04-12 18:24:19Z lindajun $
# Root level makefile 
#
# This file calls make on the src folder.

all: 
	cd src; make all

rebuild: 
	cd src; make clean; make all

clean:
	cd src; make clean
