# Project:    GMAT
# Module:     Makefile.mac for solver directory 
# Created:    Joey Gurgnaus 
# Date:       2004/02/18
#
#
# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC = DCSetupPanel.cpp SolverCreatePanel.cpp SolverEventPanel.cpp \
	SolverGoalsPanel.cpp SolverVariablesPanel.cpp VariableCreatePanel.cpp
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/gui/inc.mac
include ${INCMK}
#
