% This script prints MATLAB interface environment information
% to the report file Ex_MatlabEnv.report, located in the GMAT
% output directory.

Create MatlabFunction path pwd

Create ReportFile r
r.Filename = 'Ex_MatlabEnv.report'
r.WriteHeaders = off

Create String s path_hdr pwd_hdr blank
path_hdr = 'path()'
pwd_hdr = 'pwd()'
blank = ''

BeginMissionSequence

[s] = path
Report r path_hdr
Report r s
Report r blank

[s] = pwd
Report r pwd_hdr
Report r s
