//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
// Developed jointly by NASA/GSFC and Thinking Systems, Inc. under contract
// number S-67573-G
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#include "CommandException.hpp" // class's header file

// class constructor
CommandException::CommandException(std::string details) :
    BaseException           ("Command Exception Thrown: ", details)
{
	// insert your code here
}

// class destructor
CommandException::~CommandException()
{
	// insert your code here
}

