//$Header$
//------------------------------------------------------------------------------
//                                  NoOp
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
// Developed jointly by NASA/GSFC and Thinking Systems, Inc. under contract
// number S-67573-G
//
/**
 * Null operator for the command sequence -- typically used as a place holder
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#include "NoOp.hpp" // class's header file

// class constructor
NoOp::NoOp() :
    Command("NoOp")
{
}

// class destructor
NoOp::~NoOp()
{
}

NoOp::NoOp(const NoOp& noop) :
    Command (noop)
{}

NoOp& NoOp::operator=(const NoOp&)
{
    return *this;
}


bool NoOp::Execute(void)
{
    return true;
}

