# Project:    GMAT
# Module:     Makefile.mac for controllogic directory 
# Created:    Joey Gurgnaus 
# Date:       2004/05/21
#
#
# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC := $(wildcard *.cpp)
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/gui/inc.mac
include ${INCMK}
#
