# Project:    GMAT
# Module:     Makefile.mac for interpreter directory 
# Created:    Joey Gurgnaus 
# Date:       2003/11/13

# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC = GuiInterpreter.cpp InterpreterException.cpp Interpreter.cpp \
	ScriptInterpreter.cpp
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/base/inc.mac
include ${INCMK}
#
