//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#ifndef CELESTIALBODY_HPP
#define CELESTIALBODY_HPP

/**
 * Shell for celestial bodies
 */
class CelestialBody
{
	public:
		// class constructor
		CelestialBody();
		// class destructor
		~CelestialBody();
};

#endif // CELESTIALBODY_HPP

