//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#include "CelestialBody.hpp" // class's header file

// class constructor
CelestialBody::CelestialBody()
{
	// insert your code here
}

// class destructor
CelestialBody::~CelestialBody()
{
	// insert your code here
}

