//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#ifndef SOLARSYSTEM_HPP
#define SOLARSYSTEM_HPP

#include "gmatdefs.hpp"
/**
 * Shell for the solar system
 */
class SolarSystem
{
	public:
		// class constructor
		SolarSystem();
		// class destructor
		~SolarSystem();

      StringArray GetBodiesInUse();

protected:
      StringArray bodiesInUse;
};

#endif // SOLARSYSTEM_HPP

