//$Header$
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------




// Class automatically generated by Dev-C++ New Class wizard

#include "SolarSystem.hpp" // class's header file

// class constructor
SolarSystem::SolarSystem()
{
	// insert your code here
}

// class destructor
SolarSystem::~SolarSystem()
{
	// insert your code here
}

StringArray SolarSystem::GetBodiesInUse()
{
   return bodiesInUse;
}

