# $Id: Makefile 9461 2011-04-21 22:10:15Z lindajun $
# GMAT: General Mission Analysis Tool.
# 
#  Copyright (c) 2002-2011 United States Government as represented by the
#  Administrator of The National Aeronautics and Space Administration.
#  All Other Rights Reserved.
#
# src level makefile 
#
# This file calls make on the src subfolders.

all: 
	cd base; make all

clean:
	cd base; make clean
