# Project:    GMAT
# Module:     Makefile.mac for view directory 
# Created:    Joey Gurgnaus 
# Date:       2004/02/18
# Modified:   2005/06/29 - Cleaned up and replaced *.cpp with $(wildcard *.cpp)
#
#
# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC := $(wildcard *.cpp)
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/gui/inc.mac
include ${INCMK}
#
