//$Header: /cygdrive/p/dev/cvs/test/TestForceModel/ConsoleAppException.cpp,v 1.1 2004/03/02 06:13:35 dconway Exp $
//------------------------------------------------------------------------------
//                                  ClassName
//------------------------------------------------------------------------------
// GMAT: Goddard Mission Analysis Tool.
//
// Author: Darrel J. Conway
// Created: 2003/mm/dd
//
// Developed jointly by NASA/GSFC and Thinking Systems, Inc. under contract
// number S-67573-G
//
/**
 * Insert descriptive text here.
 *
 * @note Any notes here.
 */
//------------------------------------------------------------------------------


// Class automatically generated by Dev-C++ New Class wizard

#include "ConsoleAppException.hpp" // class's header file

// class constructor
ConsoleAppException::ConsoleAppException(std::string details) :
    BaseException       ("Console Application Execution Failed: ", details)
{
	// insert your code here
}

// class destructor
ConsoleAppException::~ConsoleAppException()
{
	// insert your code here
}

