# $Id: Makefile 7882 2010-04-12 18:22:44Z lindajun $
# Root level makefile 
#
# This file calls make on the src folder.

all: 
	cd src; make all

rebuild: 
	cd src; make clean; make all

clean:
	cd src; make clean
