# Project:    GMAT
# Module:     Makefile.mac for interpolator directory 
# Created:    Joey Gurgnaus 
# Date:       2003/11/13

# Define the marco for the top-level directories
PROJECT_ROOT    = ../..
#
# Source file for creating new library
SRC = Interpolator.cpp LinearInterpolator.cpp
#
# Define macro for using the included file 
INCMK = $(PROJECT_ROOT)/base/inc.mac
include ${INCMK}
#
