Create ImpulsiveBurn globalBurn;
Create Spacecraft globalSat;
Create Variable index;

Create ForceModel fm
fm.PrimaryBodies = {Earth}
Create Propagator prop
prop.FM = fm

Create OpenGLPlot OpenGLPlot1;
GMAT OpenGLPlot1.Add = {globalSat, Earth};

Global globalBurn globalSat

Propagate prop(globalSat) {globalSat.Earth.Periapsis}
For index = 1 : 4
    RaiseApogee(index);
    Propagate prop(globalSat) {globalSat.Earth.Periapsis}
EndFor
